name: cook_book
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  firebase_core: ^2.26.0
  firebase_database: ^10.1.1
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pomedor/
    - assets/images/products/
