// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qfwunyOe9xJKoKB4lDgzTSbTr6MIbNk',
    appId: '1:1014116330486:web:68349d6d28aa1868e675d7',
    messagingSenderId: '1014116330486',
    projectId: 'recipe-book-f3c25',
    authDomain: 'recipe-book-f3c25.firebaseapp.com',
    storageBucket: 'recipe-book-f3c25.appspot.com',
    measurementId: 'G-4KG9F0V8XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQX46krdSh6vsY3LM9oilZzZont2cXMNA',
    appId: '1:1014116330486:android:d76ea9cdf6f2d2ece675d7',
    messagingSenderId: '1014116330486',
    projectId: 'recipe-book-f3c25',
    storageBucket: 'recipe-book-f3c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5adw3LRTA8mrPxFhvXJJ9EfnfaU4jqzo',
    appId: '1:1014116330486:ios:24761829e2ec13d7e675d7',
    messagingSenderId: '1014116330486',
    projectId: 'recipe-book-f3c25',
    storageBucket: 'recipe-book-f3c25.appspot.com',
    iosBundleId: 'com.snizhanatyman.recipebook.recipebook',
  );
}
